name: PHPCS check

on:
    pull_request:
    push:
        branches:
            - develop
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    phpcs:
        name: Run PHPCS checks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  ini-values: 'memory_limit=1G'
                  coverage: none
                  tools: cs2pr

            - name: Install Composer dependencies
              run: composer update

            - name: Run PHPCS checks
              run: composer run phpcs -- --report=checkstyle > phpcs-report.xml

            - name: Show PHPCS results in PR
              if: ${{ always() && steps.phpcs.outcome == 'failure' }}
              run: cs2pr phpcs-report.xml
